version: '2'
services:
 
 registro_auditoria:
    restart: always
    container_name: modulo-registro-auditoria
    image: camiloriguer/nodejs
    ports:
     - 3789:3789
    links:
    - mongo
    
 mongo:
    restart: always
    container_name: mongo-auditoria
    image: mongo
    ports:
     - 27017:27017
    
    
 
